test: Add tests for client error console and card kitchensink
posit-dev/py-shiny pull request #1262
Opened 2024-03-28 17:32 UTC by karangattu

Fixes https://github.com/posit-dev/py-shiny/issues/1251

2024-03-28 18:05 UTC, karangattu commented on tests/playwright/deploys/shiny-client-error/test_shiny_client_error.py
> +    if "127.0.0.1:" in app_url:
If `http` not in app_url

2024-04-02 18:49 UTC, schloerke requested changes

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +                Defaults to None.
Left align parameter names. Indent parameter description. (Repeat for remaining parameter sections)

```suggestion
        value
            The expected value of the width attribute.
        timeout
            The maximum time to wait for the expectation to be fulfilled.
            Defaults to None.
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    A class representing the width container mixin.
```suggestion
    A mixin class representing the container's width.
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    A class representing the width location mixin.
```suggestion
    A mixin class representing the `loc`'s width.
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    Card control for shiny.ui.card - https://shiny.posit.co/py/api/core/ui.card.html
```suggestion
    Card control for :func:`~shiny.ui.card`
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    Locator for the card's value
Make class name within a code block

```suggestion
    `Locator` for the card's value
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    Locator for the card body
```suggestion
    `Locator` for the card title
    """
    loc_footer: Locator
    """
    `Locator` for the card footer
    """
    loc_body: Locator
    """
    `Locator` for the card body
```

2024-04-02 18:49 UTC, schloerke commented on tests/playwright/controls.py
> +    def expect_full_screen_available(
Double check if we can remove the method from valuebox as it is a card under the hood. If it is not a card, leave as is.

2024-04-04 18:37 UTC, schloerke approved these changes

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/controls.py
> +    def expect_full_screen_enabled(
You were right. Reverting name change

```suggestion
    def expect_full_screen_available(
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
> +    value_box1.expect_full_screen_enabled(True)
```suggestion
    value_box1.expect_full_screen_available(True)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
> +    value_box2.expect_full_screen_enabled(False)
```suggestion
    value_box2.expect_full_screen_available(False)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
> +    value_box3.expect_full_screen_enabled(True)
```suggestion
    value_box3.expect_full_screen_available(True)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
> +    value_box4.expect_full_screen_enabled(False)
```suggestion
    value_box4.expect_full_screen_available(False)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/components/value_box/kitchensink/test_valuebox_ks.py
> +    value_box5.expect_full_screen_enabled(False)
```suggestion
    value_box5.expect_full_screen_available(False)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/experimental/card/kitchensink/test_card_ks.py
> +    card.expect_full_screen_enabled(False)
```suggestion
    card.expect_full_screen_available(False)
```

2024-04-04 18:37 UTC, schloerke commented on tests/playwright/shiny/experimental/card/kitchensink/test_card_ks.py
> +    card.expect_full_screen_enabled(False)
```suggestion
    card.expect_full_screen_available(False)
```

2024-04-04 18:55 UTC, merged