test: Add dataframe edit tests
posit-dev/py-shiny pull request #1290
Opened 2024-04-05 16:17 UTC by karangattu

2024-04-05 19:51 UTC, schloerke approved these changes

2024-04-05 19:52 UTC, schloerke requested changes
See comments above

2024-04-05 19:54 UTC, schloerke commented on tests/playwright/controls.py
> +        ).to_have_class(class_, timeout=timeout)
Should we add another method of `expect_cell_state()` that checks for `"ready", "editing", "success", "failure"`?

(ready has no class value. The other strings map to a specific class value)

2024-04-08 19:17 UTC, karangattu commented on tests/playwright/controls.py
>              )
Not sure if I covered this one

2024-04-09 19:04 UTC, schloerke commented on tests/playwright/shiny/components/data_frame/validate_data_save/app.py
> +        time.sleep(2)
```suggestion
	# Slow down change so that we can test for "editing" state
        time.sleep(2)
```

2024-04-09 19:05 UTC, schloerke approved these changes

2024-04-09 20:18 UTC, merged