test(conftests): Refactor conftest functions to be imported as shiny.test module
posit-dev/py-shiny pull request #1413
Opened 2024-05-23 03:36 UTC by karangattu

2024-05-23 03:37 UTC, karangattu commented on shiny/test/_internal.py
> +# def x_create_doc_example_fixture(example_name: str, scope: ScopeName = "module"):
```suggestion
```

2024-05-28 18:42 UTC, schloerke commented on shiny/test/__init__.py
> +    # "expect_to_change",
```suggestion
    # # TODO-future: Find the proper location for these methods to be returned
    # "run_shiny_app",
    # "expect_to_change",
```

2024-05-28 18:44 UTC, schloerke commented on shiny/test/_conftest.py
> +        timeoutAt = datetime.datetime.now() + datetime.timedelta(seconds=timeoutSecs)
Please add some docs for the public method

2024-05-28 18:44 UTC, schloerke commented on shiny/test/_conftest.py
> +    def close(self) -> None:
Please add some docs for the public method

2024-05-28 18:44 UTC, schloerke commented on shiny/test/_conftest.py
> +    def wait_until_ready(self, timeoutSecs: float) -> None:
Please add some docs for the public method

2024-05-28 18:45 UTC, schloerke commented on shiny/test/_conftest.py
> +def run_shiny_app(
Please add some docs for the public method

2024-05-28 18:45 UTC, schloerke commented on shiny/test/_pytest.py
> +def session_page(browser: BrowserContext) -> Page:
Please add some docs for the public method

2024-05-28 18:45 UTC, schloerke commented on shiny/test/_pytest.py
> +def page(session_page: Page) -> Page:
Please add some docs for the public method

2024-05-28 18:45 UTC, schloerke commented on shiny/test/_pytest.py
> +def local_app(request: pytest.FixtureRequest) -> Generator[ShinyAppProc, None, None]:
Please add some docs for the public method

2024-05-28 18:47 UTC, schloerke commented on shiny/test/_pytest.py
> +def page(session_page: Page) -> Page:
Mention that this `page` is built on `session_page` which is maintained over the full session. What's new is `page` will visit `about:blank` to _reset_ between apps. 

Also mention that the default viewport size is set to `1920 x 1080` (1080p) for each test function.

2024-05-28 18:48 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +def local_app_fixture_gen(app: PurePath | str):
Please add some docs for the public method

2024-05-28 18:48 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +def create_app_fixture(
Please add some docs for the public method

2024-05-28 18:49 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +        # (`yield` must be on same line as `next`!)
```suggestion
```

2024-05-28 18:50 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +def local_app_fixture_gen(app: PurePath | str):
I am not sold on the function name. We should ask others for feedback

2024-05-29 18:20 UTC, schloerke requested changes

2024-05-29 18:20 UTC, schloerke commented on shiny/test/playwright.py
> +
Please rename this file to `_playwright.py` to hide it.
(This will cause many import updates)

2024-05-29 18:20 UTC, schloerke commented on tests/playwright/README.md
> +from shiny.test._internal import create_example_fixture
```suggestion
from conftest import create_example_fixture
```

2024-05-30 18:19 UTC, schloerke commented on shiny/test/_pytest.py
> +    The page is built on the session_page, which is maintained over the full session.
```suggestion

    The page is built on the session_page, which is maintained over the full session.
```

2024-05-30 18:19 UTC, schloerke commented on shiny/test/_pytest.py
> +@pytest.fixture(scope="session")
Can we move `session_page` and `page` into shiny's conftest.py? These two fixtures feel like they are too shiny specific for the first release

2024-05-30 18:19 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +def local_app_fixture_gen(app: PurePath | str):
Barret TODO:
* Let's rename this method to `run_shiny_app`. 
* The original `run_shiny_app` should be renamed to an internal method. 
* Expose the original `run_shiny_app` parameters and add `start_attempts = 3` to expose how many start attempts could be made.

2024-05-30 18:19 UTC, schloerke commented on shiny/test/fixture/_fixture.py
> +    Create a fixture for a local Shiny app.
```suggestion
    Create a fixture for a local Shiny app directory.
```

2024-05-30 19:57 UTC, schloerke approved these changes

2024-05-30 21:10 UTC, merged