Finish some todo tasks
posit-dev/py-shiny pull request #731
Opened 2023-09-13 20:26 UTC by karangattu

Address `TODO-karan` tasks.
All has a POC of how to check if new UI methods are added without making sure they have module support

2023-09-25 16:11 UTC, schloerke requested changes

2023-09-25 16:11 UTC, schloerke commented on tests/e2e/bugs/0696-resolve-id/check.py
> +)
I like this idea and where it's going. 

- [ ] Move `test_0696_resolve_id.py`'s custom expectation method into a new file (`mod_state.py`?) that can be imported into here and the original file. 
- [ ] Change class name to `ModState`
- [ ] Have expectation methods receive a `ModState` object. 
- [ ] Double check if a value is missing when creating a NamedTuple, an error is thrown.
- [ ] Have a `default_mod_state` object (which currently equals `component` above).
- [ ] Is it possible to import `mod_state` into the app to retrieve the `input_keys` and `x_input_keys`?

2023-09-25 16:11 UTC, schloerke commented on tests/e2e/controls.py
> +        # self.loc resolves to 4 elements, thus violating the strict mode requirement
```suggestion
        # self.loc resolves to multiple elements, thus violating the strict mode requirement
```

2023-09-25 16:11 UTC, schloerke commented on tests/e2e/controls.py
> +        # self.loc.scroll_into_view_if_needed(timeout=timeout)
Can these be done on `element` in the next line?

2023-09-25 16:11 UTC, schloerke commented on tests/e2e/controls.py
> +class _OverlayBase(_InputBase):
Merge in the latest from `main`. Hopefully most of the new code in the rest of the file is not double added. 

... unless there are new changes?

2023-09-25 16:11 UTC, schloerke commented on tests/e2e/controls.py
> +        self.loc.wait_for(state="visible", timeout=timeout)
Please remove comment added in #728 about adding these lines throughout controls

2023-10-02 19:07 UTC, karangattu commented on tests/e2e/inputs/input_file/app.py
> +    ui.input_file("file2", "Choose CSV File", accept=[".csv"], multiple=True),
As far I recollect, one of the challenges was when uploading multiple files, it did not show an array instead it just shows `n` files uploaded where `n` is the number of files that the user selected.

2023-10-03 04:23 UTC, karangattu commented on tests/e2e/inputs/input_file/app.py
> +    ui.input_file("file2", "Choose CSV File", accept=[".csv"], multiple=True),
I do check that `expect(file2.loc_file_display).to_have_value("2 files")`

2023-10-06 14:13 UTC, schloerke commented on tests/e2e/bugs/0696-resolve-id/check.py
> +)
Turning into comment. 

Resolving

2023-10-06 16:36 UTC, merged